/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    DriveSelector: typeof import('./src/components/DriveSelector.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputText: typeof import('primevue/inputtext')['default']
    OsSelector: typeof import('./src/components/OsSelector.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    SourceSelector: typeof import('./src/components/SourceSelector.vue')['default']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
  }
}
