package main

import (
	"embed"
	_ "embed"
	"log"
	"log/slog"
	"os"
	"time"

	"github.com/kyleaupton/flashit/internal/core"
	"github.com/kyleaupton/flashit/internal/drives"
	"github.com/kyleaupton/flashit/internal/eventbus"
	"github.com/kyleaupton/flashit/internal/logger"
	"github.com/kyleaupton/flashit/internal/service"

	"github.com/wailsapp/wails/v3/pkg/application"
)

// Wails uses Go's `embed` package to embed the frontend files into the binary.
// Any files in the frontend/dist folder will be embedded into the binary and
// made available to the frontend.
// See https://pkg.go.dev/embed for more information.

//go:embed all:frontend/dist
var assets embed.FS

// main function serves as the application's entry point. It initializes the application, creates a window,
// and starts a goroutine that emits a time-based event every second. It subsequently runs the application and
// logs any error that might occur.
func main() {
	// Check for dry-run mode via environment variable
	if os.Getenv("DRY_RUN") == "1" || os.Getenv("DRY_RUN") == "true" {
		core.DryRun = true
		log.Println("🧪 DRY-RUN MODE: Using mock drives, no real disk operations")
		drives.SetProvider(drives.MockProvider{Drives: drives.DefaultMockDrives()})
	}

	// Create a new Wails application by providing the necessary options.
	// Variables 'Name' and 'Description' are for application metadata.
	// 'Assets' configures the asset server with the 'FS' variable pointing to the frontend files.
	// 'Bind' is a list of Go struct instances. The frontend has access to the methods of these instances.
	// 'Mac' options tailor the application when running an macOS.
	app := application.New(application.Options{
		Name:        "flashit",
		Description: "A demo of using raw HTML & CSS",
		LogLevel:    slog.LevelInfo,
		Assets: application.AssetOptions{
			Handler: application.AssetFileServerFS(assets),
		},
		Mac: application.MacOptions{
			ApplicationShouldTerminateAfterLastWindowClosed: true,
		},
	})

	// Use Wails' logger for unified log format
	logger.SetLogger(app.Logger)

	// Set global event emitter for backend modules
	eventbus.SetEmitter(func(name string, data any) { app.Event.Emit(name, data) })

	jobsSvc := service.NewJobsService()
	app.RegisterService(application.NewService(jobsSvc))
	drivesSvc := service.NewDrivesService()
	app.RegisterService(application.NewService(drivesSvc))

	// TODO: Add Wails updater service when available in Wails v3
	// See: https://v3alpha.wails.io/guides/distribution/auto-updates
	// The update.json manifest is generated by the release workflow and will
	// be ready when the updater API becomes available.

	// Create a new window with the necessary options.
	// 'Title' is the title of the window.
	// 'Mac' options tailor the window when running on macOS.
	// 'BackgroundColour' is the background colour of the window.
	// 'URL' is the URL that will be loaded into the webview.
	app.Window.NewWithOptions(application.WebviewWindowOptions{
		Title:         "FlashIt",
		Width:         800,
		Height:        500,
		DisableResize: true,
		Mac: application.MacWindow{
			InvisibleTitleBarHeight: 50,
			Backdrop:                application.MacBackdropTranslucent,
			TitleBar:                application.MacTitleBarHiddenInset,
		},
		BackgroundColour: application.NewRGB(27, 38, 54),
		URL:              "/",
	})

	// Create a goroutine that emits an event containing the current time every second.
	// The frontend can listen to this event and update the UI accordingly.
	go func() {
		for {
			now := time.Now().Format(time.RFC1123)
			app.Event.Emit("time", now)
			time.Sleep(time.Second)
		}
	}()

	// Run the application. This blocks until the application has been exited.
	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
}
