// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as drives$0 from "../drives/models.js";

export function ListDrives(): $CancellablePromise<drives$0.Drive[]> {
    return $Call.ByID(3290335159).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = drives$0.Drive.createFrom;
const $$createType1 = $Create.Array($$createType0);
