// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jobs$0 from "../jobs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelJob cancels a running job by ID.
 * Returns true if the job was found and cancelled, false if not found or already completed.
 */
export function CancelJob(jobID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3452811188, jobID);
}

export function ListInstallers(): $CancellablePromise<$models.InstallerMeta[]> {
    return $Call.ByID(849630866).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListJobs(): $CancellablePromise<jobs$0.Job[]> {
    return $Call.ByID(1465115179).then(($result: any) => {
        return $$createType3($result);
    });
}

export function StartJob(req: $models.StartJobRequest): $CancellablePromise<$models.StartJobResponse> {
    return $Call.ByID(2679174400, req).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.InstallerMeta.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = jobs$0.Job.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.StartJobResponse.createFrom;
