// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum OSFamily {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OSWindows = "windows",
    OSLinux = "linux",
    OSMacOS = "macos",
};

export class Plan {
    "id": string;
    "name": string;

    /**
     * UI metadata for steps
     */
    "stepInfos": StepInfo[];
    "meta"?: { [_ in string]?: any };

    /** Creates a new Plan instance. */
    constructor($$source: Partial<Plan> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("stepInfos" in $$source)) {
            this["stepInfos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plan instance from a string or object.
     */
    static createFrom($$source: any = {}): Plan {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stepInfos" in $$parsedSource) {
            $$parsedSource["stepInfos"] = $$createField2_0($$parsedSource["stepInfos"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField3_0($$parsedSource["meta"]);
        }
        return new Plan($$parsedSource as Partial<Plan>);
    }
}

/**
 * StepInfo provides metadata about a step for UI display
 */
export class StepInfo {
    /**
     * Unique key like "writing-iso", "unmounting-disk"
     */
    "key": string;

    /**
     * Human-readable name like "Writing ISO to USB"
     */
    "name": string;

    /**
     * true for long operations with progress tracking
     */
    "hasProgress": boolean;

    /** Creates a new StepInfo instance. */
    constructor($$source: Partial<StepInfo> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hasProgress" in $$source)) {
            this["hasProgress"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): StepInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StepInfo($$parsedSource as Partial<StepInfo>);
    }
}

export class Target {
    "Family": OSFamily;
    "Version": string;
    "Arch": string;

    /** Creates a new Target instance. */
    constructor($$source: Partial<Target> = {}) {
        if (!("Family" in $$source)) {
            this["Family"] = OSFamily.$zero;
        }
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }
        if (!("Arch" in $$source)) {
            this["Arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Target instance from a string or object.
     */
    static createFrom($$source: any = {}): Target {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Target($$parsedSource as Partial<Target>);
    }
}

// Private type creation functions
const $$createType0 = StepInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
