// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum OSFamily {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OSWindows = "windows",
    OSLinux = "linux",
    OSMacOS = "macos",
};

export class Plan {
    "ID": string;
    "Name": string;
    "Steps": Step[];
    "Meta": { [_: string]: any };

    /** Creates a new Plan instance. */
    constructor($$source: Partial<Plan> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Steps" in $$source)) {
            this["Steps"] = [];
        }
        if (!("Meta" in $$source)) {
            this["Meta"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plan instance from a string or object.
     */
    static createFrom($$source: any = {}): Plan {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Steps" in $$parsedSource) {
            $$parsedSource["Steps"] = $$createField2_0($$parsedSource["Steps"]);
        }
        if ("Meta" in $$parsedSource) {
            $$parsedSource["Meta"] = $$createField3_0($$parsedSource["Meta"]);
        }
        return new Plan($$parsedSource as Partial<Plan>);
    }
}

export type Step = any;

export class Target {
    "Family": OSFamily;
    "Version": string;
    "Arch": string;

    /** Creates a new Target instance. */
    constructor($$source: Partial<Target> = {}) {
        if (!("Family" in $$source)) {
            this["Family"] = OSFamily.$zero;
        }
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }
        if (!("Arch" in $$source)) {
            this["Arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Target instance from a string or object.
     */
    static createFrom($$source: any = {}): Target {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Target($$parsedSource as Partial<Target>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
