// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const OSFamily = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OSWindows: "windows",
    OSLinux: "linux",
    OSMacOS: "macos",
};

export class Plan {
    /**
     * Creates a new Plan instance.
     * @param {Partial<Plan>} [$$source = {}] - The source object to create the Plan.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Steps" in $$source)) {
            /**
             * @member
             * @type {Step[]}
             */
            this["Steps"] = [];
        }
        if (!("Meta" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }}
             */
            this["Meta"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plan instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Plan}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Steps" in $$parsedSource) {
            $$parsedSource["Steps"] = $$createField2_0($$parsedSource["Steps"]);
        }
        if ("Meta" in $$parsedSource) {
            $$parsedSource["Meta"] = $$createField3_0($$parsedSource["Meta"]);
        }
        return new Plan(/** @type {Partial<Plan>} */($$parsedSource));
    }
}

/**
 * @typedef {any} Step
 */

export class Target {
    /**
     * Creates a new Target instance.
     * @param {Partial<Target>} [$$source = {}] - The source object to create the Target.
     */
    constructor($$source = {}) {
        if (!("Family" in $$source)) {
            /**
             * @member
             * @type {OSFamily}
             */
            this["Family"] = OSFamily.$zero;
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("Arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Target instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Target}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Target(/** @type {Partial<Target>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
