// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Drive is a normalized, cross-platform description of a physical drive.
 * For macOS, BSDName is like "disk3"; on Linux, it might be "sdb".
 */
export class Drive {
    /**
     * Creates a new Drive instance.
     * @param {Partial<Drive>} [$$source = {}] - The source object to create the Drive.
     */
    constructor($$source = {}) {
        if (!("Device" in $$source)) {
            /**
             * e.g. "/dev/disk3" (darwin), "/dev/sdb" (linux)
             * @member
             * @type {string}
             */
            this["Device"] = "";
        }
        if (!("BSDName" in $$source)) {
            /**
             * short name: "disk3" (darwin), "sdb" (linux), may be empty on Windows
             * @member
             * @type {string}
             */
            this["BSDName"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["SizeBytes"] = 0;
        }
        if (!("Model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Model"] = "";
        }
        if (!("Vendor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Vendor"] = "";
        }
        if (!("Serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Serial"] = "";
        }
        if (!("Protocol" in $$source)) {
            /**
             * "USB", "SATA", "NVMe", "Thunderbolt", etc.
             * @member
             * @type {string}
             */
            this["Protocol"] = "";
        }
        if (!("IsRemovable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsRemovable"] = false;
        }
        if (!("IsEjectable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsEjectable"] = false;
        }
        if (!("Mountpoints" in $$source)) {
            /**
             * mountpoints for any child volumes (if known)
             * @member
             * @type {string[]}
             */
            this["Mountpoints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Drive instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Drive}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mountpoints" in $$parsedSource) {
            $$parsedSource["Mountpoints"] = $$createField9_0($$parsedSource["Mountpoints"]);
        }
        return new Drive(/** @type {Partial<Drive>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
