// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Drive is a normalized, cross-platform description of a physical drive.
 * For macOS, BSDName is like "disk3"; on Linux, it might be "sdb".
 */
export class Drive {
    /**
     * e.g. "/dev/disk3" (darwin), "/dev/sdb" (linux)
     */
    "Device": string;

    /**
     * short name: "disk3" (darwin), "sdb" (linux), may be empty on Windows
     */
    "BSDName": string;
    "SizeBytes": number;
    "Model": string;
    "Vendor": string;
    "Serial": string;

    /**
     * "USB", "SATA", "NVMe", "Thunderbolt", etc.
     */
    "Protocol": string;
    "IsRemovable": boolean;
    "IsEjectable": boolean;

    /**
     * mountpoints for any child volumes (if known)
     */
    "Mountpoints": string[];

    /** Creates a new Drive instance. */
    constructor($$source: Partial<Drive> = {}) {
        if (!("Device" in $$source)) {
            this["Device"] = "";
        }
        if (!("BSDName" in $$source)) {
            this["BSDName"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("Vendor" in $$source)) {
            this["Vendor"] = "";
        }
        if (!("Serial" in $$source)) {
            this["Serial"] = "";
        }
        if (!("Protocol" in $$source)) {
            this["Protocol"] = "";
        }
        if (!("IsRemovable" in $$source)) {
            this["IsRemovable"] = false;
        }
        if (!("IsEjectable" in $$source)) {
            this["IsEjectable"] = false;
        }
        if (!("Mountpoints" in $$source)) {
            this["Mountpoints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Drive instance from a string or object.
     */
    static createFrom($$source: any = {}): Drive {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mountpoints" in $$parsedSource) {
            $$parsedSource["Mountpoints"] = $$createField9_0($$parsedSource["Mountpoints"]);
        }
        return new Drive($$parsedSource as Partial<Drive>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
