// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as drives$0 from "../drives/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jobs$0 from "../jobs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListDrives returns currently detected removable USB drives.
 * @returns {$CancellablePromise<drives$0.Drive[]>}
 */
export function ListDrives() {
    return $Call.ByID(3579943911).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.InstallerMeta[]>}
 */
export function ListInstallers() {
    return $Call.ByID(3026363171).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<jobs$0.Job[]>}
 */
export function ListJobs() {
    return $Call.ByID(3613485978).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.StartJobRequest} req
 * @returns {$CancellablePromise<string>}
 */
export function StartJob(req) {
    return $Call.ByID(3029209185, req);
}

// Private type creation functions
const $$createType0 = drives$0.Drive.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.InstallerMeta.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = jobs$0.Job.createFrom;
const $$createType5 = $Create.Array($$createType4);
