// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export class InstallerMeta {
    /**
     * Creates a new InstallerMeta instance.
     * @param {Partial<InstallerMeta>} [$$source = {}] - The source object to create the InstallerMeta.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Targets" in $$source)) {
            /**
             * @member
             * @type {core$0.Target[]}
             */
            this["Targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallerMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallerMeta}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Targets" in $$parsedSource) {
            $$parsedSource["Targets"] = $$createField2_0($$parsedSource["Targets"]);
        }
        return new InstallerMeta(/** @type {Partial<InstallerMeta>} */($$parsedSource));
    }
}

export class StartJobRequest {
    /**
     * Creates a new StartJobRequest instance.
     * @param {Partial<StartJobRequest>} [$$source = {}] - The source object to create the StartJobRequest.
     */
    constructor($$source = {}) {
        if (!("InstallerID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["InstallerID"] = "";
        }
        if (!("SourceURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SourceURL"] = "";
        }
        if (!("Checksum" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Checksum"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartJobRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartJobRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartJobRequest(/** @type {Partial<StartJobRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = core$0.Target.createFrom;
const $$createType1 = $Create.Array($$createType0);
