// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export class InstallerMeta {
    "ID": string;
    "Name": string;
    "Targets": core$0.Target[];

    /** Creates a new InstallerMeta instance. */
    constructor($$source: Partial<InstallerMeta> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Targets" in $$source)) {
            this["Targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallerMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallerMeta {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Targets" in $$parsedSource) {
            $$parsedSource["Targets"] = $$createField2_0($$parsedSource["Targets"]);
        }
        return new InstallerMeta($$parsedSource as Partial<InstallerMeta>);
    }
}

export class StartJobRequest {
    "InstallerID": string;
    "SourceLocal": string;
    "DriveID": string;

    /** Creates a new StartJobRequest instance. */
    constructor($$source: Partial<StartJobRequest> = {}) {
        if (!("InstallerID" in $$source)) {
            this["InstallerID"] = "";
        }
        if (!("SourceLocal" in $$source)) {
            this["SourceLocal"] = "";
        }
        if (!("DriveID" in $$source)) {
            this["DriveID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartJobRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartJobRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartJobRequest($$parsedSource as Partial<StartJobRequest>);
    }
}

export class StartJobResponse {
    "jobId": string;
    "stepInfos": core$0.StepInfo[];

    /** Creates a new StartJobResponse instance. */
    constructor($$source: Partial<StartJobResponse> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("stepInfos" in $$source)) {
            this["stepInfos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartJobResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): StartJobResponse {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stepInfos" in $$parsedSource) {
            $$parsedSource["stepInfos"] = $$createField1_0($$parsedSource["stepInfos"]);
        }
        return new StartJobResponse($$parsedSource as Partial<StartJobResponse>);
    }
}

// Private type creation functions
const $$createType0 = core$0.Target.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = core$0.StepInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
