// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Job {
    /**
     * Creates a new Job instance.
     * @param {Partial<Job>} [$$source = {}] - The source object to create the Job.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Plan" in $$source)) {
            /**
             * @member
             * @type {core$0.Plan | null}
             */
            this["Plan"] = null;
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["Status"] = Status.$zero;
        }
        if (!("Progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Progress"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Job}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Plan" in $$parsedSource) {
            $$parsedSource["Plan"] = $$createField1_0($$parsedSource["Plan"]);
        }
        return new Job(/** @type {Partial<Job>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusPending: "pending",
    StatusRunning: "running",
    StatusSucceeded: "succeeded",
    StatusFailed: "failed",
};

// Private type creation functions
const $$createType0 = core$0.Plan.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
