// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Job {
    "ID": string;
    "Plan": core$0.Plan | null;
    "Status": Status;
    "Progress": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;

    /** Creates a new Job instance. */
    constructor($$source: Partial<Job> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Plan" in $$source)) {
            this["Plan"] = null;
        }
        if (!("Status" in $$source)) {
            this["Status"] = Status.$zero;
        }
        if (!("Progress" in $$source)) {
            this["Progress"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     */
    static createFrom($$source: any = {}): Job {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Plan" in $$parsedSource) {
            $$parsedSource["Plan"] = $$createField1_0($$parsedSource["Plan"]);
        }
        return new Job($$parsedSource as Partial<Job>);
    }
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusPending = "pending",
    StatusRunning = "running",
    StatusSucceeded = "succeeded",
    StatusFailed = "failed",
    StatusCancelled = "cancelled",
};

// Private type creation functions
const $$createType0 = core$0.Plan.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
